In [1]:
import pandas as pd

df = pd.read_csv("../data/master_dataset_FINAL_SUBMISSION_LOCKED.csv")

df.head()

,property_id,City_clean,Locality,Price,Avg_Rent,rental_yield_pct,yield_category,investment_score,score_driver,score_rent_component,...,flood_data_level,crime_data_level,yield_unit,investment_score_scale,last_updated,assumption_notes,score_formula_version,data_status,area_category,Area_sqft_valid
0,6409ea75-c672-41cb-9c42-154916dfe04d,Chennai,Kanathur Reddikuppam,19900000.0,14000.0,0.844221,Low,67.8,Rental Yield Driven,6.7,...,State,City,Percent (%),100,2025-12-15,Flood risk applied at state level due to data ...,RY_70 + SAFETY_20 + FLOOD_10,FINAL_FROZEN,Large,2583
1,599c79b0-9ced-437a-9aca-01cdabaf3640,Chennai,Ramanathan Nagar,22500000.0,13400.0,0.714667,Low,34.5,Rental Yield Driven,5.3,...,State,City,Percent (%),100,2025-12-15,Flood risk applied at state level due to data ...,RY_70 + SAFETY_20 + FLOOD_10,FINAL_FROZEN,Large,7000
2,77077f61-127b-40a4-b751-d2a38649ac28,Chennai,Kasthuribai Nagar,10000000.0,13400.0,1.608000,Low,34.5,Rental Yield Driven,18.2,...,State,City,Percent (%),100,2025-12-15,Flood risk applied at state level due to data ...,RY_70 + SAFETY_20 + FLOOD_10,FINAL_FROZEN,Large,1320
3,9ac4fb93-ca48-4633-8533-0223036b7a45,Chennai,Naveenilaya,33300000.0,13400.0,0.482883,Low,34.5,Rental Yield Driven,2.6,...,State,City,Percent (%),100,2025-12-15,Flood risk applied at state level due to data ...,RY_70 + SAFETY_20 + FLOOD_10,FINAL_FROZEN,Large,4250
4,10505f0c-ee90-4653-88c7-91bcf8def8e1,Chennai,Avadi,4800000.0,8000.0,2.000000,Medium,69.2,Rental Yield Driven,23.4,...,State,City,Percent (%),100,2025-12-15,Flood risk applied at state level due to data ...,RY_70 + SAFETY_20 + FLOOD_10,FINAL_FROZEN,Medium,960

In [2]:
df['Price'].describe()

count    1.452800e+04
mean     1.067444e+07
std      1.867258e+07
min      1.000000e+05
25%      3.700000e+06
50%      6.500000e+06
75%      1.140000e+07
max      8.400000e+08
Name: Price, dtype: float64

In [3]:
metro_cities = [
    'Mumbai', 'Delhi', 'Bangalore', 'Chennai',
    'Hyderabad', 'Pune', 'Kolkata'
]

def realistic_price_flag(row):
    if row['City_clean'] in metro_cities and row['Price'] < 2000000:
        return False
    return True

df['price_realistic_flag'] = df.apply(realistic_price_flag, axis=1)

In [4]:
df.groupby('City_clean')['price_realistic_flag'].value_counts()

City_clean  price_realistic_flag
Bangalore   True                    4421
            False                     92
Chennai     True                    1541
            False                     54
Hyderabad   True                     539
            False                      1
Kolkata     True                    1278
            False                    114
Mumbai      True                    1278
            False                     75
New Delhi   True                    2165
Pune        True                    2610
            False                    354
Thane       True                       6
Name: count, dtype: int64

In [5]:
df = df[df['price_realistic_flag'] == True]

In [6]:
df_app = df[df['price_realistic_flag'] == True].copy()

In [7]:
df_app['price_lakh'] = (df_app['Price'] / 100000).round(2)
df_app['price_crore'] = (df_app['Price'] / 10000000).round(2)

In [8]:
df_app.groupby('City_clean')['price_lakh'].describe()

             count        mean         std   min    25%    50%     75%     max
City_clean
Bangalore   4421.0  123.932911  200.035525  20.0  55.00  79.50  135.00  8400.0
Chennai     1541.0   98.209981  126.592541  20.0  39.00  60.00  100.00  1600.0
Hyderabad    539.0  124.768534  149.303371  22.0  60.00  85.00  135.00  2150.0
Kolkata     1278.0   72.604202   86.171067  20.0  32.00  45.00   75.00  1200.0
Mumbai      1278.0  155.313083  207.160627  20.0  55.25  95.00  175.00  3000.0
New Delhi   2165.0  132.271649  275.779005   1.0  31.00  62.75  130.00  6500.0
Pune        2610.0   75.290460  135.741172  20.0  32.00  49.00   77.00  4020.0
Thane          6.0   61.333333   12.327476  49.5  52.75  56.50   70.75    78.5

In [9]:
df_app.groupby('City_clean')['price_lakh'].describe()

             count        mean         std   min    25%    50%     75%     max
City_clean
Bangalore   4421.0  123.932911  200.035525  20.0  55.00  79.50  135.00  8400.0
Chennai     1541.0   98.209981  126.592541  20.0  39.00  60.00  100.00  1600.0
Hyderabad    539.0  124.768534  149.303371  22.0  60.00  85.00  135.00  2150.0
Kolkata     1278.0   72.604202   86.171067  20.0  32.00  45.00   75.00  1200.0
Mumbai      1278.0  155.313083  207.160627  20.0  55.25  95.00  175.00  3000.0
New Delhi   2165.0  132.271649  275.779005   1.0  31.00  62.75  130.00  6500.0
Pune        2610.0   75.290460  135.741172  20.0  32.00  49.00   77.00  4020.0
Thane          6.0   61.333333   12.327476  49.5  52.75  56.50   70.75    78.5

In [10]:
df_app.to_csv(
    "master_dataset_FINAL_APP_READY.csv",
    index=False
)